export function Description ({product}){
    return(
        <div className="description_section">
            <div className="descrition_container body">
                <h2>CONDIÇÕES DE PARTICIPAÇÃO</h2>
                <p>O GÊMEOS BRASIL V.23 é um Título de Capitalização da Modalidade Filantropia Premiável, de pagamento único, emitido pela VIA CAPITALIZAÇÃO S.A. (VIACAP), Sociedade de Capitalização inscrita no CNPJ sob o Número 88.076.302/0001-94, com sede na Av. Carlos Gomes, 222, Conj. 901, Bairro Boa Vista, Porto Alegre/RS, CEP 90480-000. 
                    <strong>A contratação deste título é apropriada principalmente na hipótese de o consumidor estar interessado em contribuir com entidades beneficentes de assistência sociais, certificadas nos termos da legislação vigente, e participar de sorteio(s).</strong>
                        Ao adquirir o GÊMEOS BRASIL V.23 você concorrerá aos sorteios previstos neste Título e 100% do direito de resgate do seu Título será revertido à FEDERAÇÃO NACIONAL DAS ASSOCIAÇÕES PESTALOZZI - FENAPESTALOZZI, Entidade Filantrópica inscrita no CNPJ sob o Número 42.129.809/0001-68, com sede na ST SRTVS, 110, Quadra 701, Bloco O, Salas 496 e 497, Asa Sul, Brasília/DF, CEP 70.340-000, para utilização dos recursos em seus projetos de assistência social e nas diversas atividades da entidade, caso não haja comunicação contrária à Sociedade de Capitalização. Conheça mais sobre o trabalho e os projetos da FEDERAÇÃO NACIONAL DAS ASSOCIAÇÕES PESTALOZZI - FENAPESTALOZZI através do site www.fenapestalozzi.org.br. É obrigatório o preenchimento correto da Ficha de Cadastro no momento de aquisição do título. Antes de contratar, consulte previamente as Condições Gerais do Título, cuja versão completa está disponível para consulta no site www.susep.gov.br. Este Título de Capitalização foi aprovado pela Superintendência de Seguros Privados – SUSEP – através do Processo SUSEP nº 15414.621820/2023-40.
                    <strong>
                        Ao adquirir o GÊMEOS BRASIL V.23 você concorrerá aos sorteios previstos neste Título e 100% do direito de resgate do seu Título será revertido à FEDERAÇÃO NACIONAL DAS ASSOCIAÇÕES PESTALOZZI - FENAPESTALOZZI, Entidade Filantrópica inscrita no CNPJ sob o Número 42.129.809/0001-68, com sede na ST SRTVS, 110, Quadra 701, Bloco O, Salas 496 e 497, Asa Sul, Brasília/DF, CEP 70.340-000, para utilização dos recursos em seus projetos de assistência social e nas diversas atividades da entidade, caso não haja comunicação contrária à Sociedade de Capitalização. Conheça mais sobre o trabalho e os projetos da FEDERAÇÃO NACIONAL DAS ASSOCIAÇÕES PESTALOZZI - FENAPESTALOZZI através do site www.fenapestalozzi.org.br. É obrigatório o preenchimento correto da Ficha de Cadastro no momento de aquisição do título. Antes de contratar, consulte previamente as Condições Gerais do Título, cuja versão completa está disponível para consulta no site www.susep.gov.br. Este Título de Capitalização foi aprovado pela Superintendência de Seguros Privados – SUSEP – através do Processo SUSEP nº 15414.621820/2023-40. 
                    </strong>
                    <strong>
                    Ao adquirir o GÊMEOS BRASIL V.23 o Subscritor irá concorrer aos Sorteios da Modalidade “Loteria Federal”: Você concorre em 1 sorteio apurado com base na extração da Loteria Federal. Para concorrer aos sorteios previstos nesta modalidade o Título contém impresso 1 Número(s) da Sorte, não repetido(s) na mesma série, compreendido(s) no intervalo entre “000.000” e “999.999. Para identificar o título sorteado, ao menos um Número da Sorte impresso no título deverá coincidir com o número formado pela combinação do primeiro prêmio da extração da Loteria Federal adicionando-se ao seu final o primeiro algarismo do segundo prêmio da Loteria Federal. Regra de Aproximação: Caso a combinação contemplada, apurada na forma, não tenha sido distribuída a um participante será aplicada a seguinte regra de aproximação: será contemplado o participante que possuir o próximo Número da Sorte imediatamente superior ao efetivamente apurado, na forma acima, e assim sucessivamente até que seja identificado um participante contemplado em cada uma das premiações acima. Caso, por qualquer motivo, a Loteria Federal não venha a realizar a extração na data prevista de sorteio, será considerada, para fins do disposto neste Capítulo, a extração seguinte que vier a ser por ela realizada. Caso a Caixa Econômica Federal suspenda definitivamente as extrações da Loteria Federal do Brasil, ou modifique as referidas extrações de forma que não mais coincidam com as regras deste sorteio, ou haja qualquer impedimento à vinculação da Loteria Federal aos sorteios previstos, a VIA Capitalização S.A, num prazo máximo de trinta dias, promoverá o sorteio não realizado com aparelhos próprios e em local de livre acesso ao público, sob fiscalização de auditoria independente e em idênticas condições às previstas originalmente no título, dando prévia e ampla divulgação do fato. 
                    </strong>

                </p>
                <p>PREMIAÇÃO - {product} </p>
                <p>CONFORME DETALHADO NAS CONDIÇÕES DE PARTICIPAÇÃO.</p>
                <p>SUGESTÃO DE USO DO PRÊMIO LÍQUIDO TOTAL DE R$ 92.075,00</p>
            
            </div>
        </div>
    )
}